[project]
name = "stocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "appdirs>=1.4.4",
    "flask>=3.1.1",
    "pandas>=2.2.3",
    "plotly>=6.2.0",
    "setuptools>=80.9.0",
    "yfinance>=0.2.66",
]
